dependencies:
  - name: elasticsearch
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 1.15.1
  - name: memcached
    version: 2.4.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: postgresql
    version: 3.7.0
    repository: https://kubernetes-charts.storage.googleapis.com/
